// ReSharper disable InconsistentNaming
namespace DemoApi.Models;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

public class SurveryResult
{
    public int? RecordNo { get; set; }
    public DateTime? endtime { get; set; }
    public DateTime? starttime { get; set; }
    public bool? EG01 { get; set; }
    public string? EG_02 { get; set; }
    public string? EG_04 { get; set; }
    public int? EG_03 { get; set; }
    public string? EG_03_open { get; set; }
    public int? EG_03B { get; set; }
    public string? EG_03B_open { get; set; }
    public bool? EG_07_1 { get; set; }
    public bool? EG_07_2 { get; set; }
    public bool? EG_07_3 { get; set; }
    public bool? EG_07_4 { get; set; }
    public bool? EG_07_5 { get; set; }
    public bool? EG_07_6 { get; set; }
    public bool? EG_07_7 { get; set; }
    public bool? EG_07_8 { get; set; }
    public bool? EG_07_9 { get; set; }
    public bool? EG_07_10 { get; set; }
    public bool? EG_07_11 { get; set; }
    public bool? EG_07_12 { get; set; }
    public bool? EG_07_966 { get; set; }
    public bool? EG_07_977 { get; set; }
    public int? EG_08 { get; set; }
    public int? EG_09_01 { get; set; }
    public bool? EG_10_1 { get; set; }
    public bool? EG_10_2 { get; set; }
    public bool? EG_10_3 { get; set; }
    public bool? EG_10_4 { get; set; }
    public bool? EG_10_5 { get; set; }
    public bool? EG_10_6 { get; set; }
    public bool? EG_10_966 { get; set; }
    public bool? EG_15_1 { get; set; }
    public bool? EG_15_2 { get; set; }
    public bool? EG_15_3 { get; set; }
    public bool? EG_15_4 { get; set; }
    public bool? EG_15_5 { get; set; }
    public bool? EG_15_6 { get; set; }
    public bool? EG_15_966 { get; set; }
    public bool? EG_11_1 { get; set; }
    public bool? EG_11_2 { get; set; }
    public bool? EG_11_3 { get; set; }
    public bool? EG_11_4 { get; set; }
    public bool? EG_11_5 { get; set; }
    public bool? EG_11_6 { get; set; }
    public bool? EG_11_966 { get; set; }
    public int? EG_13 { get; set; }
    public bool? EG_12_1 { get; set; }
    public bool? EG_12_2 { get; set; }
    public bool? EG_12_3 { get; set; }
    public bool? EG_12_4 { get; set; }
    public bool? EG_12_5 { get; set; }
    public bool? EG_12_6 { get; set; }
    public bool? EG_12_966 { get; set; }
    public bool? EG_14_1 { get; set; }
    public bool? EG_14_2 { get; set; }
    public bool? EG_14_3 { get; set; }
    public bool? EG_14_4 { get; set; }
    public bool? EG_14_5 { get; set; }
    public bool? EG_14_6 { get; set; }
    public bool? EG_14_966 { get; set; }
    public bool? EG_23_1 { get; set; }
    public bool? EG_23_2 { get; set; }
    public bool? EG_23_3 { get; set; }
    public bool? EG_23_4 { get; set; }
    public bool? EG_23_5 { get; set; }
    public bool? EG_23_6 { get; set; }
    public bool? EG_23_966 { get; set; }
    public int? BestAd01 { get; set; }
    public string? BestAd_02 { get; set; }
    public string? BestAd_03 { get; set; }
    public string? BestAd_04 { get; set; }
    public bool? BestAd_05_1 { get; set; }
    public bool? BestAd_05_2 { get; set; }
    public bool? BestAd_05_3 { get; set; }
    public bool? BestAd_05_4 { get; set; }
    public bool? BestAd_05_5 { get; set; }
    public bool? BestAd_05_6 { get; set; }
    public bool? BestAd_05_7 { get; set; }
    public bool? BestAd_05_8 { get; set; }
    public bool? BestAd_05_966 { get; set; }
    public bool? BestAd_05_977 { get; set; }
    public bool? BestAd_06_1 { get; set; }
    public bool? BestAd_06_2 { get; set; }
    public bool? BestAd_06_3 { get; set; }
    public bool? BestAd_06_4 { get; set; }
    public bool? BestAd_06_5 { get; set; }
    public bool? BestAd_06_6 { get; set; }
    public bool? BestAd_06_7 { get; set; }
    public bool? BestAd_06_8 { get; set; }
    public bool? BestAd_06_9 { get; set; }
    public bool? BestAd_06_10 { get; set; }
    public bool? BestAd_06_11 { get; set; }
    public bool? BestAd_06_12 { get; set; }
    public bool? BestAd_06_966 { get; set; }
    public bool? BestAd_06_977 { get; set; }
    public int? BestAd_07 { get; set; }
    public string? BestAd_07_open { get; set; }
    public int? profile_julesage { get; set; }
    public int? profile_gender { get; set; }
    public int? profile_GOR { get; set; }
    public int? profile_gross_household { get; set; }
    public int? profile_education_level { get; set; }
    public int? profile_household_size_rcy { get; set; }
    public int? UK18_Sept_2020_f_0 { get; set; }
    public int? UK18_Sept_2020_f_1 { get; set; }
    public int? UK18_Sept_2020_f_2 { get; set; }
    public int? UK18_Sept_2020_f_3 { get; set; }
    public int? UK18_Sept_2020_f_4 { get; set; }
    public int? UK18_Sept_2020_f_5 { get; set; }
    public int? UK18_Sept_2020_f_6 { get; set; }
    public int? UK18_Sept_2020_f_7 { get; set; }
    public int? UK18_Sept_2020_f_8 { get; set; }
    public double? weight { get; set; }
}

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
